spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" 
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth
          uri: http://localhost:9092
          predicates:
            - Path=/api/auth/**  
             
        - id: backend
          uri: http://localhost:9091
          predicates:
            - Path=/api/**
          filters:
            - name: JwtValidationFilter
  main:
    allow-circular-references: true         

  application:
   name: employeewellness-gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/ 
    enabled: true 
  instance:
    prefer-ip-address: true
    
server:
  port: 8765